### ISSUE TITLE
Only 35 heroes extracted from HotS PTR 2.38.0.68406

### ISSUE THREAD

**Issue by pastelmind** [koliva8245/HeroesDataParser#10]
* OS: Windows 7 (x86)
* HDP version: v2.3.0
* HotS version: HotS PTR 2.38.0.68406
* Command line: `.\heroesdata.exe -s 'C:\Program Files\Heroes of the Storm Public Test' --json -l enus -l kokr -o .\`

HeroesDataParser extracts only 35 heroes from the latest PTR. Notably, the reworked Kerrigan and Brightwing are missing. See [gist for the output JSON file](https://gist.github.com/pastelmind/53b15a62972f1e2d1d12fadb4c6af179).

**Comment by koliva8245** [comment]
Blizzard made all the files and folder names lowercase.  Has been fixed, though this won't go out until Wednesday's balance patch.

You can either wait until Wednesday, compile the code yourself, or download this zip file
[heroes_68406(ptr)_enus_kokr.zip](https://github.com/koliva8245/HeroesDataParser/files/2390886/heroes_68406.ptr._enus_kokr.zip).

**Comment by pastelmind** [comment]
Thank you for the quick reply, and for providing a fixed output file.
