### ISSUE TITLE
Abilities

### ISSUE THREAD

**Issue by MGatner** [koliva8245/HeroesDataParser#11]
Working on some downstream dependencies and trying to add ability icons... Your tool is awesome and splits things out nicely, but it does lump abilities under "talents" with no distinction. Rather than sorting through them individually I'd love to see this split out programmatically and dumped into its own folder (for -e). Glad to help with the handling thereof, but thought I'd start with a report.

**Comment by koliva8245** [comment]
Done, v2.4.0 for Tuesday.

**Comment by MGatner** [comment]
Awesome! Thanks for the quick response.
