### ISSUE TITLE
Non-standard single quote

### ISSUE THREAD

**Issue by MGatner** [koliva8245/HeroesDataParser#12]
Some apostrophes in the JSON file are coming through as special character "[RIGHT SINGLE QUOTATION MARK](http://www.fileformat.info/info/unicode/char/2019/index.htm)" (e.g. in Dragon's Breath) and some are standard single quote (e.g. Rite of Rak'Shir). These actually match differently in most parsers and databases:

```
php > echo ord("’");
226
php > echo ord("'");
39
```

I assume this is something inconsistent in the game files, but any chance it is standard-izable?

**Comment by koliva8245** [comment]
Is it inconsistent or is the right single quote used just for possession?  Either way I'm not going to modify the text from the game files, that includes any typos as well.

**Comment by MGatner** [comment]
It's definitely inconsistent, both see use within names and as possessives, across names and descriptions both.
I agree with your decision to dump game data as is. For anyone doing automatic parsing here's my example workaround:

`$ability['name'] = str_replace("\u{2019}", "'", $ability['name']);`
