### ISSUE TITLE
[X-Request] Ability ranges

### ISSUE THREAD

**Issue by MGatner** [koliva8245/HeroesDataParser#13]
heroes-talents downstream has a feature request for ability ranges that would be very easily done if they were parsed out by HeroesDataParser
https://github.com/heroespatchnotes/heroes-talents/issues/11

**Comment by koliva8245** [comment]
Can't do, way too difficult.

**Comment by MGatner** [comment]
I was afraid of that. Recommending dropping the other request on heroes-talents.
