### ISSUE TITLE
subAbilities have wrong ability type

### ISSUE THREAD

**Issue by MGatner** [koliva8245/HeroesDataParser#17]
It looks like subAbilities are getting Hotkey for their abilityType attribute. E.g.:
TychusOdinAnnihilate
"abilityType": "Q"

Version 2.6.0

Command:
HeroesData --description 3 --storagePath "$hotsDir" --extract all --json --outputDirectory "$targetDir/HeroesDataParser" --heroWarnings --localization all

**Comment by koliva8245** [comment]
It's supposed to.  That Tychus one is correct.

**Comment by MGatner** [comment]
Ah I see the other abilities have the same. My mistake. I was looking at the named ones ("Passive", "Heroic", "Trait") and wondering why the subAbilities weren't the same - but they are! Thanks for clarifying
