### ISSUE TITLE
Passive Talent Differentiation

### ISSUE THREAD

**Issue by MGatner** [koliva8245/HeroesDataParser#18]
I see in https://github.com/koliva8245/HeroesDataParser/issues/5 you noted multiple ability talents can't be parsed out. I'm wondering if there's any way to differentiate an ability upgrade versus a truly passive talent. Example: Zeratul's ZeratulPsionicStrength provides passive damage increase to his kit, not tied to any ability; "Passive". Zeratul's ZeratulWarpSkirmisherTalent enhances Vorpal Blade specifically, but also marked "Passive". Right now I'm checking the talent icon to see if it corresponds to an ability icon, but I doubt that is consistently reliable across all heroes.

**Comment by koliva8245** [comment]
Maybe..
