### ISSUE TITLE
Talent Ability/subAbility Differentiation

### ISSUE THREAD

**Issue by MGatner** [koliva8245/HeroesDataParser#19]
The abilityType field on talents is super helpful for connecting talents back to the ability they modify. Another case of difficulty differentiating is when a hero has subAbilities with talents. Example: Valeera's ValeeraSinisterStrikeMutilate and ValeeraAmbushDeathFromAbove are both abilityType "Q" but modify here Q ability and her Q subAbility respectively.
If the game files contain a way to distinguish these would it be possible to include that in the pared JSON? Again, using the talent icon to match it up at the moment but not feeling confident that is consistent.

**Comment by koliva8245** [comment]
Just like #18, maybe.  I'll take a look.

**Comment by MGatner** [comment]
Thanks so much! Not a huge issue, but I have found a few instances where matching off icon is misleading.
