### ISSUE TITLE
Gamestrings could not be loaded

### ISSUE THREAD

**Issue by MGatner** [koliva8245/HeroesDataParser#26]
Automated extraction after today's patch failed for -all localizations with:

Error: Gamestrings could not be loaded. Check if localization is installed in game client.

**Comment by koliva8245** [comment]
Work's fine for me.  Can you attach an error log?

**Comment by MGatner** [comment]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Heroes Data Parser (2.7.0)
  --https://github.com/koliva8245/HeroesDataParser
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 'Heroes of the Storm' directory
Localization(s): enus dede eses esmx frfr itit kokr plpl ptbr ruru zhcn zhtw 

Loading local CASC storage...please wait
######################################################################## 100%
Finished in 40 seconds 729 milliseconds

Hots Version Build: 2.40.1.70616

Loading xml files...
   720 xml files loaded
Finished in 1 seconds 696 milliseconds

[enus.stormdata]
Loading game strings...
  3050 Full Tooltips
  2587 Short Tooltips
    87 Hero descriptions
    92 Hero names
   949 Unit names
  3075 Ability/talent names
 29960 Other strings
Finished in 1 seconds 53 milliseconds

Loading OverrideData...
Loaded HeroOverrides.xml
Finished in 0 seconds 91 milliseconds

Parsing tooltips...
  3050 / 3050 total full tooltips
  2587 / 2587 total short tooltips
    87 / 87 total hero descriptions
    92 / 92 total hero names
   949 / 949 total unit names
  3075 / 3075 total ability/talent names
 29960 / 29960 total other strings

  3021 parsed full tooltips
  2578 parsed short tooltips
    86 parsed hero descriptions
    92 parsed hero names
   949 parsed unit names
  3075 parsed ability/talent names
 29788 parsed other strings
    29 invalid full tooltips
     9 invalid short tooltips
     1 invalid hero descriptions
     0 invalid hero names
     0 invalid unit names
     0 invalid ability/talent names
   172 invalid other strings
Finished in 39 seconds 963 milliseconds

Parsing hero data...
    84 / 84 total heroes
    84 successfully parsed heroes
Finished in 8 seconds 677 milliseconds

Parsing award data...
    39 successfully parsed awards
Finished in 0 seconds 41 milliseconds

Verifying output data...
[Abathur] has less than 3 basic abilities
[Cassia] has more than 1 weapon
[Chen] [Chen Earth] LifeRegenerationRateScaling is 0
[Chen] [Chen Fire] LifeRegenerationRateScaling is 0
[Chen] [Chen Storm] LifeRegenerationRateScaling is 0
[Greymane] has more than 1 weapon
[Lunara] has more than 1 weapon
[Raynor] has more than 1 weapon
[Rexxar] has more than 1 weapon
[The Lost Vikings] has more than 3 basic abilities
[Leoric] [LeoricDrainEssence] ShortTooltip is null or empty
[Leoric] [LeoricGhastlySwing] ShortTooltip is null or empty
[Nazeebo] [WitchDoctorGargantuanStomp] ShortTooltip is null or empty
[The Lost Vikings] [LostVikingsLongboatRaidMortar] ShortTooltip is null or empty
[Tychus] [TychusOdinThrusters] ShortTooltip is null or empty
15 warnings (18 ignored)

Creating output (enus).../var/folders/jm/cnwr9zj13cg22rhpkp0cmh_w0000gn/T/tmp.RAxhy2cX
Writing json file(s)...Done.

[dede.stormdata]
Loading game strings...
  3050 Full Tooltips
  2587 Short Tooltips
    87 Hero descriptions
    92 Hero names
   949 Unit names
  3075 Ability/talent names
 29960 Other strings
Finished in 13 seconds 125 milliseconds

Loading OverrideData...
Loaded HeroOverrides.xml
Finished in 0 seconds 19 milliseconds

Parsing tooltips...
  3050 / 3050 total full tooltips
  2587 / 2587 total short tooltips
    87 / 87 total hero descriptions
    92 / 92 total hero names
   949 / 949 total unit names
  3075 / 3075 total ability/talent names
 29960 / 29960 total other strings

  3029 parsed full tooltips
  2578 parsed short tooltips
    86 parsed hero descriptions
    92 parsed hero names
   949 parsed unit names
  3075 parsed ability/talent names
 29766 parsed other strings
    21 invalid full tooltips
     9 invalid short tooltips
     1 invalid hero descriptions
     0 invalid hero names
     0 invalid unit names
     0 invalid ability/talent names
   194 invalid other strings
Finished in 43 seconds 173 milliseconds

Parsing hero data...
    84 / 84 total heroes
    84 successfully parsed heroes
Finished in 7 seconds 233 milliseconds

Parsing award data...
    39 successfully parsed awards
Finished in 0 seconds 19 milliseconds

Verifying output data...
[Abathur] [Symbiont] Energy > 0 and EnergyType is NONE
[Abathur] [Symbiont] Life is 0
[Abathur] [Symbiont] LifeRegenerationRateScaling is 0
[Abathur] [Symbiont] LifeScaling is 0
[Abathur] has less than 3 basic abilities
[Cassia] has more than 1 weapon
[Chen] [Erdgeist] LifeRegenerationRateScaling is 0
[Chen] [Feuergeist] LifeRegenerationRateScaling is 0
[Chen] [Sturmgeist] LifeRegenerationRateScaling is 0
[Graumähne] [Fluch der Worgen] Life is 0
[Graumähne] [Fluch der Worgen] LifeRegenerationRateScaling is 0
[Graumähne] [Fluch der Worgen] LifeScaling is 0
[Graumähne] [Fluch der Worgen] Sight is 0
[Graumähne] [Fluch der Worgen] Speed is 0
[Graumähne] has more than 1 weapon
[Lost Vikings] has more than 3 basic abilities
[Lost Vikings] has no weapons
[Lost Vikings] Life is 0
[Lost Vikings] LifeRegenerationRateScaling is 0
[Lost Vikings] LifeScaling is 0
[Lost Vikings] Sight is 0
[Lunara] has more than 1 weapon
[Raynor] has more than 1 weapon
[Rexxar] has more than 1 weapon
[Leoric] [LeoricDrainEssence] ShortTooltip is null or empty
[Leoric] [LeoricGhastlySwing] ShortTooltip is null or empty
[Lost Vikings] [LostVikingsLongboatRaidMortar] ShortTooltip is null or empty
[Nazeebo] [WitchDoctorGargantuanStomp] ShortTooltip is null or empty
[Tychus] [TychusOdinThrusters] ShortTooltip is null or empty
29 warnings (4 ignored)

Creating output (dede).../var/folders/jm/cnwr9zj13cg22rhpkp0cmh_w0000gn/T/tmp.RAxhy2cX
Writing json file(s)...Done.

[eses.stormdata]
Loading game strings...
Error: Gamestrings could not be loaded. Check if localization is installed in game client.

[esmx.stormdata]
Loading game strings...
Error: Gamestrings could not be loaded. Check if localization is installed in game client.

[frfr.stormdata]
Loading game strings...
Error: Gamestrings could not be loaded. Check if localization is installed in game client.

[itit.stormdata]
Loading game strings...
Error: Gamestrings could not be loaded. Check if localization is installed in game client.

[kokr.stormdata]
Loading game strings...
Error: Gamestrings could not be loaded. Check if localization is installed in game client.

[plpl.stormdata]
Loading game strings...
Error: Gamestrings could not be loaded. Check if localization is installed in game client.

[ptbr.stormdata]
Loading game strings...
Error: Gamestrings could not be loaded. Check if localization is installed in game client.

[ruru.stormdata]
Loading game strings...
Error: Gamestrings could not be loaded. Check if localization is installed in game client.

[zhcn.stormdata]
Loading game strings...
Error: Gamestrings could not be loaded. Check if localization is installed in game client.

[zhtw.stormdata]
Loading game strings...
Error: Gamestrings could not be loaded. Check if localization is installed in game client.

Extracting portrait files...
Error extracting file: storm_ui_ingame_hero_leaderboard_yrel.dds
--> One or more errors occurred. (The remote server returned an error: (429) Too Many Requests.)

Error extracting file: ui_targetportrait_hero_orphea.dds
--> One or more errors occurred. (The remote server returned an error: (429) Too Many Requests.)
Done.
Extracting match award icon files...Done.
Extracting abilityTalent icon files...Done.

HDP has completed [2 out of 12 successful].

**Comment by MGatner** [comment]
```
Error: Gamestrings could not be loaded. Check if localization is installed in game client.   at HeroesData.Program.InitializeGameStringData(Localization localization) in C:\projects\heroesdataparser\HeroesData\Program.cs:line 544
   at HeroesData.Program.Execute() in C:\projects\heroesdataparser\HeroesData\Program.cs:line 232
```

**Comment by MGatner** [comment]
```
One or more errors occurred. (The remote server returned an error: (429) Too Many Requests.)   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at CASCLib.CDNIndexHandler.OpenDataFile(IndexEntry entry) in C:\projects\heroesdataparser\CASCExplorer\CascLib\CDNIndexHandler.cs:line 178
   at CASCLib.CASCHandlerBase.OpenFileOnlineInternal(IndexEntry idxInfo, MD5Hash key) in C:\projects\heroesdataparser\CASCExplorer\CascLib\CASCHandlerBase.cs:line 85
   at CASCLib.CASCHandler.OpenFileOnline(MD5Hash key) in C:\projects\heroesdataparser\CASCExplorer\CascLib\CASCHandler.cs:line 238
   at CASCLib.CASCHandlerBase.OpenFile(MD5Hash key) in C:\projects\heroesdataparser\CASCExplorer\CascLib\CASCHandlerBase.cs:line 75
   at CASCLib.CASCHandler.OpenFile(UInt64 hash) in C:\projects\heroesdataparser\CASCExplorer\CascLib\CASCHandler.cs:line 193
   at HeroesData.Loader.GameStrings.CASCGameStringData.ParseNewHeroes() in C:\projects\heroesdataparser\HeroesData.Loader\GameStrings\CASCGameStringData.cs:line 59
   at HeroesData.Loader.GameStrings.CASCGameStringData.ParseGameStringFiles() in C:\projects\heroesdataparser\HeroesData.Loader\GameStrings\CASCGameStringData.cs:line 26
   at HeroesData.Program.InitializeGameStringData(Localization localization) in C:\projects\heroesdataparser\HeroesData\Program.cs:line 539
```

**Comment by MGatner** [comment]
I've run it two more times and a few of the localizations worked but still got the error on most.

**Comment by koliva8245** [comment]
There should be an error file called `Exception_gamestrings_<localization>_<datetime string>.txt`

**Comment by MGatner** [comment]
That's what was in https://github.com/koliva8245/HeroesDataParser/issues/26#issuecomment-442652470 - there are 19 of them, I just copied the one

**Comment by koliva8245** [comment]
Same issue - https://github.com/koliva8245/HeroesDataParser/issues/21

The issue is it's timing out from an http request (429 - Too many Requests).  When the CASC library I'm using attempts to open a file, it needs to decrypt/decode it first from a encoding key found locally.  If such key does not exists or failed to decode, then it attempts to grab the key from a blizzard cdn.  

Your're hitting the cdn too many times in a short time frame.

So the problem might be that your game client isn't fully updated for each individual locale.  Try switching to each local and see if you perform an update.

**Comment by koliva8245** [comment]
Not that I know of.  Good news is you don't have to do the updates again for future patches, at least until you get the 429 error again.

**Comment by MGatner** [comment]
That is good news. Thanks again for the help! Glad to have some resolution to lingering #21 as well
