### ISSUE TITLE
[Feature Request] New field

### ISSUE THREAD

**Issue by MGatner** [koliva8245/HeroesDataParser#33]
I just learned about HeroPlaystyleFlags - those seem really interesting! Would it be hard to add those to the extractor?

Reference: https://www.reddit.com/r/u_TalesNT/comments/adf47c/comment/edhc0ct

**Comment by MGatner** [comment]
FYI Lost Vikings are still missing descriptors after 3.2.0

**Comment by koliva8245** [comment]
That's because The Lost Vikings itself isn't a hero.  Baleog, Erik, and Olaf are the heroes.
