### ISSUE TITLE
wrong name for Tassadar's Archon and Dimensional Shift

### ISSUE THREAD

**Issue by stuaroo** [koliva8245/HeroesDataParser#4]
v1.1.0; Windows 10; dotnet global tool

Several Tassadar talents and abilities are being output with the same incorrect name `Phase Shift`.  This applies to:

* Dimensional Shift, basic ability
* Archon, heroic ability
* Archon, level 10 talent
* Twilight Archon, level 20 talent

It's odd because all these button names really are set to Phase Shift in the GameStrings file for some reason.

* Ex: in GameStrings at `mods/heroesdata.stormmod/enus.stormdata/LocalizedData/GameStrings.txt`
* button name for Archon is: `Button/Name/TassadarArchon=Phase Shift`

**Comment by koliva8245** [comment]
Fixed.

The button names are being manually set to a game string.

For example, Tassadar's Archon ability name is being set to `Button/Name/TassadarArchonSelectButton`

```
  <CButton id="TassadarArchon" parent="StormButtonParent">
    <Name value="Button/Name/TassadarArchonSelectButton" />
     ...
  </CButton>
```

**Comment by stuaroo** [comment]
Ahh, that makes more sense, thanks for the super quick fix!
