### ISSUE TITLE
Anubarak and LostVikings missing trait in v4.1.0

### ISSUE THREAD

**Issue by pastelmind** [koliva8245/HeroesDataParser#43]
* HeroesDataParser version: 4.1.0 (FDE)
* Platform: Windows 10 Enterprise (Korean)
* Game Version: 2.46.1.75132

When extracting output with the following command:
```
~\hdp\HeroesData 'H:\Heroes of the Storm' -o . -l kokr -l enus --json
```

The resulting JSON files are missing Anub'arak's trait, Scarab Host.

Also, the Lost Vikings' trait (Viking Hoard) is present in each of the individual viking units (HeroBaleog, HeroErik, HeroOlaf), but missing in the top-level `LostVikings.abilities` object. I assume this is unintentional, as the rest of the Viking abilities are there.

**Comment by koliva8245** [comment]
Actually it was intentional, but I will add all the individual Viking unit abilities to the Viking's hero controller as it will make it easier to get all their abilities.
