### ISSUE TITLE
Malformed color value in <s> tags in tooltips

### ISSUE THREAD

**Issue by pastelmind** [koliva8245/HeroesDataParser#44]
* HeroesDataParser version: 4.1.0 (FDE)
* Platform: Windows 10 Enterprise (Korean)
* Game Version: 2.46.1.75132

When extracting output with the following command:

```
~\hdp\HeroesData 'H:\Heroes of the Storm' -o . -l kokr -l enus --json
```
 
Tooltips for skills/talents that have "two abilities in one" (e.g. Total Mayhem (Junkrat), Undying (Leoric)) have malformed color tags:

```json
        {
          "nameId": "JunkratTotalMayhem",
          "buttonId": "JunkratTotalMayhem",
          "name": "Total Mayhem",
          "icon": "storm_ui_icon_junkrat_bomb_pack.png",
          "shortTooltip": "Drop grenades upon death",
          "fullTooltip": "Upon dying, drop <c val=\"bfd4fd\">5</c> grenades that explode after <c val=\"bfd4fd\">0.75</c> seconds, each dealing <c val=\"bfd4fd\">250~~0.04~~</c> damage to nearby enemies. Deals <c val=\"bfd4fd\">75%</c> less damage to Structures.<n/><n/><s val=\"cbe8ff-ffffff\">Detonate Mine</s><n/><n/>Detonate an active Concussion Mine.",
          "abilityType": "Trait",
          "isPassive": true
        }
```

In this case, the opening `<s>` tag for "Detonate Mine" is `<s val=\"cbe8ff-ffffff\">`

**Comment by koliva8245** [comment]
Not malformed, it's a color gradient, start at `cbe8ff`, end at `ffffff`. 

However after thinking it over, I'm probably going to revert the auto-replace for style `<s>` tags as it contains other info for probably styling/formatting the text.

**Comment by koliva8245** [comment]
I removed the second half of the gradient, and added the name of the style as a new attribute.
So `<s val=\"cbe8ff-ffffff\">` becomes `<s val=\"cbe8ff\" name=\"StandardTooltipHeader\">`

**Comment by pastelmind** [comment]
Thank you! I did not know it was supposed to be a color gradient. Was this a HDP thing only, or does the game use color gradients in tooltips? I don't remember seeing text with gradients in-game.

By the way, what was the reason behind decoding color style names to color values? It feels like stripping away semantics.

**Comment by koliva8245** [comment]
It uses gradients ingame, although the some text hardly looks like a gradient, probably because of other attributes.  If your going to match the color of the ingame text, just match it the best you can.

I decoded it so it would be easier to get the value. 
For `<c>` tags its just a constant with a value, so it should be fine, unless maybe you need the constant name.
For `<s>` tag, its a style with formatting attributes, so I will add the variable name back.

Also stripping the gradient was not a good idea, so I'll add that back.
