### ISSUE TITLE
Missing Abilities

### ISSUE THREAD

**Issue by MGatner** [koliva8245/HeroesDataParser#46]
There are a bunch ability links to missing abilities:
* AmazonFendApproach (Cassia)
* AmazonFendChannel (Cassia)
* AnaHealingDartDetachableBoxMagazine (Ana)
* AnubarakLegionOfBeetlesVisual (Anubarak)
* 'AnubarakLegionOfBeetles' for Anub'arak
* 'ArtanisTwinBladesCharge' for Artanis
* 'ArtanisTwinBladesCharge' for Artanis
* 'DVaMechTraitAbilityDoesNothing' for D.Va
* 'DVaMechTraitEmergencyShieldingCooldownAbility' for D.Va
* 'DVaPilotCallMechMEKAfall' for D.Va
* 'BrightwingSoothingMistDummyCooldown' for Brightwing
* 'FenixShieldCapacitorVisual' for Fenix
* 'HanzoNaturalAgility' for Hanzo
* 'IllidanThrillOfBattle' for Illidan
* 'LucioHighFiveApproach' for Lúcio
* 'MedivhPortal1' for Medivh
* 'MurkyMarchoftheMurlocsNeverEndingMurlocsTalent' for Murky
* 'NecromancerCursedStrikesDisplayAbility' for Xul
* 'NexusHunterFinalStrikeAIChannel' for Qhira
* 'NexusHunterFinalStrikeAICancel' for Qhira
* 'NovaCloakCooldownDisplay' for Nova
* 'NovaAttackDummy' for Nova
* 'RagnarosBigRagSulfurasSmash' for Ragnaros
* 'RexxarMishaFollow' for Rexxar
* 'RexxarMishaFollowCancel' for Rexxar
* 'RexxarMishaCharge' for Rexxar
* 'SamuroCriticalStrikeDummy' for Samuro
* 'SamuroBladestorm' for Samuro
* 'SamuroIllusionMasterDummy' for Samuro
* 'SamuroHeroicAbilityIllusionMaster' for Samuro
* 'TassadarPsionicStormSecondStrike' for Tassadar
* 'VarianChargeApproach' for Varian
* 'ZeratulCloakCooldownDisplay' for Zeratul
* 'ZeratulShadowAssault' for Zeratul
* 'ZeratulShadowAssaultCharge' for Zeratul
* 'ZuljinRegenerationForestMedicine' for Zul'jin

**Comment by koliva8245** [comment]
You can just ignore all these. Some are "hidden" abilities, some no longer exist. I'll try to find a way to remove them though.
