### ISSUE TITLE
The ability that a talent affects

### ISSUE THREAD

**Issue by dkwingsmt** [koliva8245/HeroesDataParser#5]
Is it possible to extract the ability that a talent affects? Such as whether a talent affects Q, W, E, or passive, etc.

Thanks for the parser. Used it today for the first time and it's very handy.

**Comment by koliva8245** [comment]
I'll look into.

**Comment by koliva8245** [comment]
It is done.  The `AbilityType` will be `Q, W, E, Heroic, Z, Trait, Active, or Passive`. Basically it should be the same as the Talents section in hero collection.


Be on the lookout for incorrect values, as this is quite hard to get.

**Comment by dkwingsmt** [comment]
Thanks a ton. Just in case, have you considered the case of talents that enhance multiple skills?

**Comment by koliva8245** [comment]
Not possible.  They show up as `Passive`, like for Malfurion's Level 16 `Nature's Balance'.
