### ISSUE TITLE
incorrect cooldowns

### ISSUE THREAD

**Issue by stuaroo** [koliva8245/HeroesDataParser#6]
v1.1.1; Windows 10; dotnet global tool

Kinda wish I would've checked your branches before running my compare, but oh well, at least you get a bunch of examples to test against!  I've found quite a few differences between cooldowns in-game and cooldowns outputted.  Here's the list of differences for abilities and talents in a couple tables:

| Hero | Ability Name | Output value | Actual value |
| :--- | :--- | :--: | :---: | 
| Varian | Colossus Smash | 0.0625 | 20 |
| Lucio | Sound Barrier | 0.0625 | 80 |
| Kael'thas | Verdant Spheres | 0.0625 | 6 |
| Illidan | The Hunt | 0.5 | 100 |
| Greymane | Inner Beast | 999.0 | 20 |
| Gazlowe | Deth Lazor | 0.5 | 12 |
| Dehaka | Burrow | 0.5 | 20 |
| D.Va | Defense Matrix | 0.0625 | 10 |
| D.Va | Bunny Hop | 1.0 | 100 |
| D.Va | Boosters | 0.0625 | 9 |
| Chromie | Slowing Sands | 0.125 | 5 |
| Alarak | Deadly Charge | 60.0 | 45 |

| Hero | Talent Name | Output value | Actual value |
| :--- | :--- | :--: | :---: | 
| Deckard | Sapphire/Ruby/Emerald | 0.5 | 30 |
| Valeera | Crippling Poison/Wound Poison | 0.5 | 15 |
| Zagara | Envenomed Spines | 0.5 | 30 |
| Uther | Benediction | 0.5 | 60 |
| Thrall | Spirit Shield | 0.75 | 45 |
| Rexxar | Feign Death | 0.5 | 35 |
| Ragnaros | Submerge | 0.5 | 90 |
| Junkrat | Spread Volley | 0.125 | 30 |
| Gul'dan | Demonic Circle | 1.0 | 60 |
| Chromie | Time Out | 0.5 | 60 |

I noticed some general trends with cooldowns for the generic talents:

* Spell Shield talent (Zeratul, Zagara, Sylvanas, Uther, Kharazim)
    * outputs `0.5`, no cooldown listed in game (is this toggle cooldown maybe?)
* Ice Block talent (Brightwing, Nazeebo, Cho/Molten Block)
    * outputs `0.5`, should be `60` seconds
* Bribe-like talents (Brightwing/Pixie Charm, Falstad/Wingman, Murky/A Fishy Deal, Nova/Covert Mission)
    * outputs `0.25`, no cooldown listed in game

Finally there are a bunch of things with a cooldown that do not list one in game. Here's a list with the cooldown that gets outputted in `()`:

* Abilities 
    * Rexxar/Misha, Focus! `(0.125)`, Lucio/Crossfade `(0.5)`, Gul'dan/Life Tap `(0.5)`, Fenix/Weapon Modes `(0.5)`
* Mounts
    * Medivh/Raven Form `(1.0)`, Lunara/Dryad's Swiftness `(30.0)`
* Talents 
    * Zagara/Infest `(0.5)`, Thrall/Ancestral Wrath `(1.0)`, Ragnaros/Catching Fire `(30.0)`, Medivh/Portal Mastery `(0.125)`, Li-Ming/Archon: Pure Power `(0.5)`, Illidan/Blades of Azzinoth `(8.0)`

**Comment by koliva8245** [comment]
Thanks for the list. I do know about the incorrect cooldowns.  My latest code changes in the branches should fix a lot of these, among some other things as well.

**Comment by koliva8245** [comment]
All these should be fixed.
