### ISSUE TITLE
Extra cooldowns

### ISSUE THREAD

**Issue by stuaroo** [koliva8245/HeroesDataParser#8]
v2.0.1; Windows 10; dotnet global tool

Found a couple talents and an ability with cooldowns that don't appear to have cooldowns in-game:

* Cho | The Will of Cho | 60 seconds
* Gall | The Will of Gall | 60 seconds
    * The tooltip for the Will of Gall is "Takedowns permanently increase the bonus of Ogre Rage by 2%."  Since there's no activateable portion, I can't see what a cooldown would do on those two talents.
* Lunara | Dryad's Swiftness | 30 seconds
    * Typically Lunara's Z doesn't do anything, but it does get a 30-second activateable bit if you take the level 20 Galloping Gait, so perhaps that's relevant?

Also, I have a related question that will probably be easier to ask here rather than opening yet another issue.  I had never noticed before that Dehaka's Essence Collection has different tooltips and cooldowns between the store page and in-game:

* Store version
    * full tooltip: "Killing an enemy Hero will grant 10 Essence and Minion kills grant 2 Essence. Each Essence consumed heals 29 (+4% per level) health over 5 seconds. A maximum of 50 Essence can be stored. Can be cast while channeling."
    * cooldown: **1** second
* In-game version
    * full tooltip: "Gain 10 Essence from Takedowns and 2 Essence from nearby Minions dying.  Activate to consume all Essence and heal Dehaka for 29 (+4% per level) Health over 5 seconds for each Essence stored.  Maximum of 50 Essence.  Can be cast during Drag and Burrow."
    * cooldown: **5** seconds

Currently the tool outputs the in-game version, but previously it had been using the store page version (which is part of the reason why I noticed the difference at all).  Are your plans moving forward to use the in-game version whenever differences occur?

**Comment by koliva8245** [comment]
It should output the in-game version.  The store version for Dehaka is incorrect.

**Comment by stuaroo** [comment]
Sounds good, I'll keep that in mind when comparing things in the future, thanks!
