### ISSUE TITLE
Mana and scaling consistency

### ISSUE THREAD

**Issue by stuaroo** [koliva8245/HeroesDataParser#9]
v2.1.0; Windows 10; dotnet global tool

The majority of scaling values (e.g. basic attack damage, health, health regen) are outputting with base level 0 values.  However for Heroes that use Mana, currently the output is:

```json
"energy": {
  "energyAmount": 500.0,
  "type": "Mana",
  "energyRegenRate": 3.0
}
```

Correct me if I'm wrong, but I thought 500 mana and 3.0 regen rate are actually level 1 values?  For consistency, shouldn't this use level 0 values?

Also, would it be possible to add mana scaling and mana regen scaling when energy type is Mana?

**Comment by koliva8245** [comment]
Well.. they are both the level 0 and level 1 values.


Also, both don't have scaling values, they have a flat value increase individually for each level. Each one is set to 10 for Mana and 0.0976 for Mana regeneration.  

I'm not sure if I want to add these, even though the values are all the same for each level, it could technically change.

**Comment by koliva8245** [comment]
I decided not to add the mana "scale" values, instead I will update the readme/wiki to explain the scale values and note the values for mana.

The values for everything are all the starting values and all, except mana, have scaling applied starting at level 1 (from 0 to 1). Mana, like I said doesn't have scaling, instead it gets up to 29 veterency-what-cha-ma-call-its (I don't remember right now) starting at level 2 (from 1 to 2).

**Comment by stuaroo** [comment]
Sounds good to me, that's probably the best way to explain the starting values and how they increase.

**Comment by koliva8245** [comment]
Reference to [wiki](https://github.com/koliva8245/HeroesDataParser/wiki/Output-Help)
